/**
 */
package br.ufes.inf.nemo.frameweb.model.frameweb.provider;

import br.ufes.inf.nemo.frameweb.model.frameweb.util.FramewebAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class FramewebItemProviderAdapterFactory extends FramewebAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public FramewebItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.FramewebProject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FramewebProjectItemProvider framewebProjectItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.FramewebProject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFramewebProjectAdapter() {
		if (framewebProjectItemProvider == null) {
			framewebProjectItemProvider = new FramewebProjectItemProvider(this);
		}

		return framewebProjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.FramewebModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FramewebModelItemProvider framewebModelItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.FramewebModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFramewebModelAdapter() {
		if (framewebModelItemProvider == null) {
			framewebModelItemProvider = new FramewebModelItemProvider(this);
		}

		return framewebModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.FrameworkProfile} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FrameworkProfileItemProvider frameworkProfileItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.FrameworkProfile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFrameworkProfileAdapter() {
		if (frameworkProfileItemProvider == null) {
			frameworkProfileItemProvider = new FrameworkProfileItemProvider(this);
		}

		return frameworkProfileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.EntityModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityModelItemProvider entityModelItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.EntityModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityModelAdapter() {
		if (entityModelItemProvider == null) {
			entityModelItemProvider = new EntityModelItemProvider(this);
		}

		return entityModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.NavigationModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NavigationModelItemProvider navigationModelItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.NavigationModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNavigationModelAdapter() {
		if (navigationModelItemProvider == null) {
			navigationModelItemProvider = new NavigationModelItemProvider(this);
		}

		return navigationModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.ApplicationModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ApplicationModelItemProvider applicationModelItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.ApplicationModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createApplicationModelAdapter() {
		if (applicationModelItemProvider == null) {
			applicationModelItemProvider = new ApplicationModelItemProvider(this);
		}

		return applicationModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.PersistenceModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PersistenceModelItemProvider persistenceModelItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.PersistenceModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPersistenceModelAdapter() {
		if (persistenceModelItemProvider == null) {
			persistenceModelItemProvider = new PersistenceModelItemProvider(this);
		}

		return persistenceModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.DomainAssociation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainAssociationItemProvider domainAssociationItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.DomainAssociation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainAssociationAdapter() {
		if (domainAssociationItemProvider == null) {
			domainAssociationItemProvider = new DomainAssociationItemProvider(this);
		}

		return domainAssociationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.VersionAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VersionAttributeItemProvider versionAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.VersionAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVersionAttributeAdapter() {
		if (versionAttributeItemProvider == null) {
			versionAttributeItemProvider = new VersionAttributeItemProvider(this);
		}

		return versionAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.IdAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IdAttributeItemProvider idAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.IdAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIdAttributeAdapter() {
		if (idAttributeItemProvider == null) {
			idAttributeItemProvider = new IdAttributeItemProvider(this);
		}

		return idAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.LOBAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LOBAttributeItemProvider lobAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.LOBAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLOBAttributeAdapter() {
		if (lobAttributeItemProvider == null) {
			lobAttributeItemProvider = new LOBAttributeItemProvider(this);
		}

		return lobAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.EmbeddedAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EmbeddedAttributeItemProvider embeddedAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.EmbeddedAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEmbeddedAttributeAdapter() {
		if (embeddedAttributeItemProvider == null) {
			embeddedAttributeItemProvider = new EmbeddedAttributeItemProvider(this);
		}

		return embeddedAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.DecimalAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DecimalAttributeItemProvider decimalAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.DecimalAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDecimalAttributeAdapter() {
		if (decimalAttributeItemProvider == null) {
			decimalAttributeItemProvider = new DecimalAttributeItemProvider(this);
		}

		return decimalAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.DateTimeAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DateTimeAttributeItemProvider dateTimeAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.DateTimeAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDateTimeAttributeAdapter() {
		if (dateTimeAttributeItemProvider == null) {
			dateTimeAttributeItemProvider = new DateTimeAttributeItemProvider(this);
		}

		return dateTimeAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.Page} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PageItemProvider pageItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.Page}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPageAdapter() {
		if (pageItemProvider == null) {
			pageItemProvider = new PageItemProvider(this);
		}

		return pageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.DAOInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DAOInterfaceItemProvider daoInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.DAOInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDAOInterfaceAdapter() {
		if (daoInterfaceItemProvider == null) {
			daoInterfaceItemProvider = new DAOInterfaceItemProvider(this);
		}

		return daoInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.DAOClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DAOClassItemProvider daoClassItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.DAOClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDAOClassAdapter() {
		if (daoClassItemProvider == null) {
			daoClassItemProvider = new DAOClassItemProvider(this);
		}

		return daoClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.DAORealization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DAORealizationItemProvider daoRealizationItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.DAORealization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDAORealizationAdapter() {
		if (daoRealizationItemProvider == null) {
			daoRealizationItemProvider = new DAORealizationItemProvider(this);
		}

		return daoRealizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.FrontControllerClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FrontControllerClassItemProvider frontControllerClassItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.FrontControllerClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFrontControllerClassAdapter() {
		if (frontControllerClassItemProvider == null) {
			frontControllerClassItemProvider = new FrontControllerClassItemProvider(this);
		}

		return frontControllerClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.IOParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IOParameterItemProvider ioParameterItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.IOParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIOParameterAdapter() {
		if (ioParameterItemProvider == null) {
			ioParameterItemProvider = new IOParameterItemProvider(this);
		}

		return ioParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.ResultDependency} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResultDependencyItemProvider resultDependencyItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.ResultDependency}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResultDependencyAdapter() {
		if (resultDependencyItemProvider == null) {
			resultDependencyItemProvider = new ResultDependencyItemProvider(this);
		}

		return resultDependencyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.NavigationAssociation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NavigationAssociationItemProvider navigationAssociationItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.NavigationAssociation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNavigationAssociationAdapter() {
		if (navigationAssociationItemProvider == null) {
			navigationAssociationItemProvider = new NavigationAssociationItemProvider(this);
		}

		return navigationAssociationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.FrontControllerMethod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FrontControllerMethodItemProvider frontControllerMethodItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.FrontControllerMethod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFrontControllerMethodAdapter() {
		if (frontControllerMethodItemProvider == null) {
			frontControllerMethodItemProvider = new FrontControllerMethodItemProvider(this);
		}

		return frontControllerMethodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.ServiceClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceClassItemProvider serviceClassItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.ServiceClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceClassAdapter() {
		if (serviceClassItemProvider == null) {
			serviceClassItemProvider = new ServiceClassItemProvider(this);
		}

		return serviceClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.ServiceInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceInterfaceItemProvider serviceInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.ServiceInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceInterfaceAdapter() {
		if (serviceInterfaceItemProvider == null) {
			serviceInterfaceItemProvider = new ServiceInterfaceItemProvider(this);
		}

		return serviceInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.ServiceGeneralization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceGeneralizationItemProvider serviceGeneralizationItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.ServiceGeneralization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceGeneralizationAdapter() {
		if (serviceGeneralizationItemProvider == null) {
			serviceGeneralizationItemProvider = new ServiceGeneralizationItemProvider(this);
		}

		return serviceGeneralizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.ServiceControllerAssociation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceControllerAssociationItemProvider serviceControllerAssociationItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.ServiceControllerAssociation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceControllerAssociationAdapter() {
		if (serviceControllerAssociationItemProvider == null) {
			serviceControllerAssociationItemProvider = new ServiceControllerAssociationItemProvider(this);
		}

		return serviceControllerAssociationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.DomainClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainClassItemProvider domainClassItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.DomainClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainClassAdapter() {
		if (domainClassItemProvider == null) {
			domainClassItemProvider = new DomainClassItemProvider(this);
		}

		return domainClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.FrontControllerDependency} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FrontControllerDependencyItemProvider frontControllerDependencyItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.FrontControllerDependency}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFrontControllerDependencyAdapter() {
		if (frontControllerDependencyItemProvider == null) {
			frontControllerDependencyItemProvider = new FrontControllerDependencyItemProvider(this);
		}

		return frontControllerDependencyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.PageDependency} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PageDependencyItemProvider pageDependencyItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.PageDependency}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPageDependencyAdapter() {
		if (pageDependencyItemProvider == null) {
			pageDependencyItemProvider = new PageDependencyItemProvider(this);
		}

		return pageDependencyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.DAOServiceAssociation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DAOServiceAssociationItemProvider daoServiceAssociationItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.DAOServiceAssociation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDAOServiceAssociationAdapter() {
		if (daoServiceAssociationItemProvider == null) {
			daoServiceAssociationItemProvider = new DAOServiceAssociationItemProvider(this);
		}

		return daoServiceAssociationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.DomainMethod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainMethodItemProvider domainMethodItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.DomainMethod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainMethodAdapter() {
		if (domainMethodItemProvider == null) {
			domainMethodItemProvider = new DomainMethodItemProvider(this);
		}

		return domainMethodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.DAOAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DAOAttributeItemProvider daoAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.DAOAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDAOAttributeAdapter() {
		if (daoAttributeItemProvider == null) {
			daoAttributeItemProvider = new DAOAttributeItemProvider(this);
		}

		return daoAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.ServiceMethod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceMethodItemProvider serviceMethodItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.ServiceMethod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceMethodAdapter() {
		if (serviceMethodItemProvider == null) {
			serviceMethodItemProvider = new ServiceMethodItemProvider(this);
		}

		return serviceMethodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.ServiceAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceAttributeItemProvider serviceAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.ServiceAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceAttributeAdapter() {
		if (serviceAttributeItemProvider == null) {
			serviceAttributeItemProvider = new ServiceAttributeItemProvider(this);
		}

		return serviceAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.DAOMethod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DAOMethodItemProvider daoMethodItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.DAOMethod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDAOMethodAdapter() {
		if (daoMethodItemProvider == null) {
			daoMethodItemProvider = new DAOMethodItemProvider(this);
		}

		return daoMethodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.DomainPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainPackageItemProvider domainPackageItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.DomainPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainPackageAdapter() {
		if (domainPackageItemProvider == null) {
			domainPackageItemProvider = new DomainPackageItemProvider(this);
		}

		return domainPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.ViewPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ViewPackageItemProvider viewPackageItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.ViewPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createViewPackageAdapter() {
		if (viewPackageItemProvider == null) {
			viewPackageItemProvider = new ViewPackageItemProvider(this);
		}

		return viewPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.ControllerPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ControllerPackageItemProvider controllerPackageItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.ControllerPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createControllerPackageAdapter() {
		if (controllerPackageItemProvider == null) {
			controllerPackageItemProvider = new ControllerPackageItemProvider(this);
		}

		return controllerPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.PersistencePackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PersistencePackageItemProvider persistencePackageItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.PersistencePackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPersistencePackageAdapter() {
		if (persistencePackageItemProvider == null) {
			persistencePackageItemProvider = new PersistencePackageItemProvider(this);
		}

		return persistencePackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.ApplicationPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ApplicationPackageItemProvider applicationPackageItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.ApplicationPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createApplicationPackageAdapter() {
		if (applicationPackageItemProvider == null) {
			applicationPackageItemProvider = new ApplicationPackageItemProvider(this);
		}

		return applicationPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.UIComponent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UIComponentItemProvider uiComponentItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.UIComponent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUIComponentAdapter() {
		if (uiComponentItemProvider == null) {
			uiComponentItemProvider = new UIComponentItemProvider(this);
		}

		return uiComponentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.ResultType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResultTypeItemProvider resultTypeItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.ResultType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResultTypeAdapter() {
		if (resultTypeItemProvider == null) {
			resultTypeItemProvider = new ResultTypeItemProvider(this);
		}

		return resultTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.DomainGeneralization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainGeneralizationItemProvider domainGeneralizationItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.DomainGeneralization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainGeneralizationAdapter() {
		if (domainGeneralizationItemProvider == null) {
			domainGeneralizationItemProvider = new DomainGeneralizationItemProvider(this);
		}

		return domainGeneralizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.UIComponentField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UIComponentFieldItemProvider uiComponentFieldItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.UIComponentField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUIComponentFieldAdapter() {
		if (uiComponentFieldItemProvider == null) {
			uiComponentFieldItemProvider = new UIComponentFieldItemProvider(this);
		}

		return uiComponentFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.TagLib} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TagLibItemProvider tagLibItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.TagLib}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTagLibAdapter() {
		if (tagLibItemProvider == null) {
			tagLibItemProvider = new TagLibItemProvider(this);
		}

		return tagLibItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.Tag} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TagItemProvider tagItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.Tag}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTagAdapter() {
		if (tagItemProvider == null) {
			tagItemProvider = new TagItemProvider(this);
		}

		return tagItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.NavigationCompositionPart} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NavigationCompositionPartItemProvider navigationCompositionPartItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.NavigationCompositionPart}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNavigationCompositionPartAdapter() {
		if (navigationCompositionPartItemProvider == null) {
			navigationCompositionPartItemProvider = new NavigationCompositionPartItemProvider(this);
		}

		return navigationCompositionPartItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.NavigationCompositionWhole} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NavigationCompositionWholeItemProvider navigationCompositionWholeItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.NavigationCompositionWhole}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNavigationCompositionWholeAdapter() {
		if (navigationCompositionWholeItemProvider == null) {
			navigationCompositionWholeItemProvider = new NavigationCompositionWholeItemProvider(this);
		}

		return navigationCompositionWholeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.ResultSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResultSetItemProvider resultSetItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.ResultSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResultSetAdapter() {
		if (resultSetItemProvider == null) {
			resultSetItemProvider = new ResultSetItemProvider(this);
		}

		return resultSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.PageConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PageConstraintItemProvider pageConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.PageConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPageConstraintAdapter() {
		if (pageConstraintItemProvider == null) {
			pageConstraintItemProvider = new PageConstraintItemProvider(this);
		}

		return pageConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.ResultConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResultConstraintItemProvider resultConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.ResultConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResultConstraintAdapter() {
		if (resultConstraintItemProvider == null) {
			resultConstraintItemProvider = new ResultConstraintItemProvider(this);
		}

		return resultConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.MethodConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MethodConstraintItemProvider methodConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.MethodConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMethodConstraintAdapter() {
		if (methodConstraintItemProvider == null) {
			methodConstraintItemProvider = new MethodConstraintItemProvider(this);
		}

		return methodConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.ChainingConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChainingConstraintItemProvider chainingConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.ChainingConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChainingConstraintAdapter() {
		if (chainingConstraintItemProvider == null) {
			chainingConstraintItemProvider = new ChainingConstraintItemProvider(this);
		}

		return chainingConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.NavigationGeneralization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NavigationGeneralizationItemProvider navigationGeneralizationItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.NavigationGeneralization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNavigationGeneralizationAdapter() {
		if (navigationGeneralizationItemProvider == null) {
			navigationGeneralizationItemProvider = new NavigationGeneralizationItemProvider(this);
		}

		return navigationGeneralizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.DomainConstraints} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainConstraintsItemProvider domainConstraintsItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.DomainConstraints}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainConstraintsAdapter() {
		if (domainConstraintsItemProvider == null) {
			domainConstraintsItemProvider = new DomainConstraintsItemProvider(this);
		}

		return domainConstraintsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.DAOGeneralization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DAOGeneralizationItemProvider daoGeneralizationItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.DAOGeneralization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDAOGeneralizationAdapter() {
		if (daoGeneralizationItemProvider == null) {
			daoGeneralizationItemProvider = new DAOGeneralizationItemProvider(this);
		}

		return daoGeneralizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.MappingLib} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MappingLibItemProvider mappingLibItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.MappingLib}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMappingLibAdapter() {
		if (mappingLibItemProvider == null) {
			mappingLibItemProvider = new MappingLibItemProvider(this);
		}

		return mappingLibItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.ClassMapping} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClassMappingItemProvider classMappingItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.ClassMapping}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClassMappingAdapter() {
		if (classMappingItemProvider == null) {
			classMappingItemProvider = new ClassMappingItemProvider(this);
		}

		return classMappingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.AttributeMapping} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeMappingItemProvider attributeMappingItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.AttributeMapping}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeMappingAdapter() {
		if (attributeMappingItemProvider == null) {
			attributeMappingItemProvider = new AttributeMappingItemProvider(this);
		}

		return attributeMappingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.DomainGeneralizationSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainGeneralizationSetItemProvider domainGeneralizationSetItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.DomainGeneralizationSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainGeneralizationSetAdapter() {
		if (domainGeneralizationSetItemProvider == null) {
			domainGeneralizationSetItemProvider = new DomainGeneralizationSetItemProvider(this);
		}

		return domainGeneralizationSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.Controller} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ControllerItemProvider controllerItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.Controller}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createControllerAdapter() {
		if (controllerItemProvider == null) {
			controllerItemProvider = new ControllerItemProvider(this);
		}

		return controllerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.TagProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TagPropertyItemProvider tagPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.TagProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTagPropertyAdapter() {
		if (tagPropertyItemProvider == null) {
			tagPropertyItemProvider = new TagPropertyItemProvider(this);
		}

		return tagPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.ResultProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResultPropertyItemProvider resultPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.ResultProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResultPropertyAdapter() {
		if (resultPropertyItemProvider == null) {
			resultPropertyItemProvider = new ResultPropertyItemProvider(this);
		}

		return resultPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.ClassMappingPropery} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClassMappingProperyItemProvider classMappingProperyItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.ClassMappingPropery}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClassMappingProperyAdapter() {
		if (classMappingProperyItemProvider == null) {
			classMappingProperyItemProvider = new ClassMappingProperyItemProvider(this);
		}

		return classMappingProperyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.AttributeMappingProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeMappingPropertyItemProvider attributeMappingPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.AttributeMappingProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeMappingPropertyAdapter() {
		if (attributeMappingPropertyItemProvider == null) {
			attributeMappingPropertyItemProvider = new AttributeMappingPropertyItemProvider(this);
		}

		return attributeMappingPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.ServiceRealization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceRealizationItemProvider serviceRealizationItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.ServiceRealization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceRealizationAdapter() {
		if (serviceRealizationItemProvider == null) {
			serviceRealizationItemProvider = new ServiceRealizationItemProvider(this);
		}

		return serviceRealizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.NavigationGeneralizationSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NavigationGeneralizationSetItemProvider navigationGeneralizationSetItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.NavigationGeneralizationSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNavigationGeneralizationSetAdapter() {
		if (navigationGeneralizationSetItemProvider == null) {
			navigationGeneralizationSetItemProvider = new NavigationGeneralizationSetItemProvider(this);
		}

		return navigationGeneralizationSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.DAOGeneralizationSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DAOGeneralizationSetItemProvider daoGeneralizationSetItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.DAOGeneralizationSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDAOGeneralizationSetAdapter() {
		if (daoGeneralizationSetItemProvider == null) {
			daoGeneralizationSetItemProvider = new DAOGeneralizationSetItemProvider(this);
		}

		return daoGeneralizationSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.ServiceGeneralizationSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceGeneralizationSetItemProvider serviceGeneralizationSetItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.ServiceGeneralizationSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceGeneralizationSetAdapter() {
		if (serviceGeneralizationSetItemProvider == null) {
			serviceGeneralizationSetItemProvider = new ServiceGeneralizationSetItemProvider(this);
		}

		return serviceGeneralizationSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.SemanticPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SemanticPackageItemProvider semanticPackageItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.SemanticPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSemanticPackageAdapter() {
		if (semanticPackageItemProvider == null) {
			semanticPackageItemProvider = new SemanticPackageItemProvider(this);
		}

		return semanticPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.IRI} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IRIItemProvider iriItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.IRI}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIRIAdapter() {
		if (iriItemProvider == null) {
			iriItemProvider = new IRIItemProvider(this);
		}

		return iriItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.VocabularyModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VocabularyModelItemProvider vocabularyModelItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.VocabularyModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVocabularyModelAdapter() {
		if (vocabularyModelItemProvider == null) {
			vocabularyModelItemProvider = new VocabularyModelItemProvider(this);
		}

		return vocabularyModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.Vocabulary} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VocabularyItemProvider vocabularyItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.Vocabulary}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVocabularyAdapter() {
		if (vocabularyItemProvider == null) {
			vocabularyItemProvider = new VocabularyItemProvider(this);
		}

		return vocabularyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.Axiom} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AxiomItemProvider axiomItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.Axiom}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAxiomAdapter() {
		if (axiomItemProvider == null) {
			axiomItemProvider = new AxiomItemProvider(this);
		}

		return axiomItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.Annotation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnnotationItemProvider annotationItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.Annotation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnnotationAdapter() {
		if (annotationItemProvider == null) {
			annotationItemProvider = new AnnotationItemProvider(this);
		}

		return annotationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.VocabularyConstraints} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VocabularyConstraintsItemProvider vocabularyConstraintsItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.VocabularyConstraints}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVocabularyConstraintsAdapter() {
		if (vocabularyConstraintsItemProvider == null) {
			vocabularyConstraintsItemProvider = new VocabularyConstraintsItemProvider(this);
		}

		return vocabularyConstraintsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.VocabularyAssociation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VocabularyAssociationItemProvider vocabularyAssociationItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.VocabularyAssociation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVocabularyAssociationAdapter() {
		if (vocabularyAssociationItemProvider == null) {
			vocabularyAssociationItemProvider = new VocabularyAssociationItemProvider(this);
		}

		return vocabularyAssociationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.VocabularyProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VocabularyPropertyItemProvider vocabularyPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.VocabularyProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVocabularyPropertyAdapter() {
		if (vocabularyPropertyItemProvider == null) {
			vocabularyPropertyItemProvider = new VocabularyPropertyItemProvider(this);
		}

		return vocabularyPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.ObjectProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectPropertyItemProvider objectPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.ObjectProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectPropertyAdapter() {
		if (objectPropertyItemProvider == null) {
			objectPropertyItemProvider = new ObjectPropertyItemProvider(this);
		}

		return objectPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.DataProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataPropertyItemProvider dataPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.DataProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataPropertyAdapter() {
		if (dataPropertyItemProvider == null) {
			dataPropertyItemProvider = new DataPropertyItemProvider(this);
		}

		return dataPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.VocabularyDataType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VocabularyDataTypeItemProvider vocabularyDataTypeItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.VocabularyDataType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVocabularyDataTypeAdapter() {
		if (vocabularyDataTypeItemProvider == null) {
			vocabularyDataTypeItemProvider = new VocabularyDataTypeItemProvider(this);
		}

		return vocabularyDataTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.NamedIndividual} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NamedIndividualItemProvider namedIndividualItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.NamedIndividual}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNamedIndividualAdapter() {
		if (namedIndividualItemProvider == null) {
			namedIndividualItemProvider = new NamedIndividualItemProvider(this);
		}

		return namedIndividualItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.VocabularyClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VocabularyClassItemProvider vocabularyClassItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.VocabularyClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVocabularyClassAdapter() {
		if (vocabularyClassItemProvider == null) {
			vocabularyClassItemProvider = new VocabularyClassItemProvider(this);
		}

		return vocabularyClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.AnonymousIndividual} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnonymousIndividualItemProvider anonymousIndividualItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.AnonymousIndividual}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnonymousIndividualAdapter() {
		if (anonymousIndividualItemProvider == null) {
			anonymousIndividualItemProvider = new AnonymousIndividualItemProvider(this);
		}

		return anonymousIndividualItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.VocabularyLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VocabularyLiteralItemProvider vocabularyLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.VocabularyLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVocabularyLiteralAdapter() {
		if (vocabularyLiteralItemProvider == null) {
			vocabularyLiteralItemProvider = new VocabularyLiteralItemProvider(this);
		}

		return vocabularyLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.DomainVocabularyAssociation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainVocabularyAssociationItemProvider domainVocabularyAssociationItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.DomainVocabularyAssociation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainVocabularyAssociationAdapter() {
		if (domainVocabularyAssociationItemProvider == null) {
			domainVocabularyAssociationItemProvider = new DomainVocabularyAssociationItemProvider(this);
		}

		return domainVocabularyAssociationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.DomainVocabularyProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainVocabularyPropertyItemProvider domainVocabularyPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.DomainVocabularyProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainVocabularyPropertyAdapter() {
		if (domainVocabularyPropertyItemProvider == null) {
			domainVocabularyPropertyItemProvider = new DomainVocabularyPropertyItemProvider(this);
		}

		return domainVocabularyPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.DomainAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainAttributeItemProvider domainAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.DomainAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainAttributeAdapter() {
		if (domainAttributeItemProvider == null) {
			domainAttributeItemProvider = new DomainAttributeItemProvider(this);
		}

		return domainAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.DomainProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainPropertyItemProvider domainPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.DomainProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainPropertyAdapter() {
		if (domainPropertyItemProvider == null) {
			domainPropertyItemProvider = new DomainPropertyItemProvider(this);
		}

		return domainPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.FrontControllerTemplate} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FrontControllerTemplateItemProvider frontControllerTemplateItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.FrontControllerTemplate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFrontControllerTemplateAdapter() {
		if (frontControllerTemplateItemProvider == null) {
			frontControllerTemplateItemProvider = new FrontControllerTemplateItemProvider(this);
		}

		return frontControllerTemplateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.DITemplate} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DITemplateItemProvider diTemplateItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.DITemplate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDITemplateAdapter() {
		if (diTemplateItemProvider == null) {
			diTemplateItemProvider = new DITemplateItemProvider(this);
		}

		return diTemplateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link br.ufes.inf.nemo.frameweb.model.frameweb.ORMTemplate} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ORMTemplateItemProvider ormTemplateItemProvider;

	/**
	 * This creates an adapter for a {@link br.ufes.inf.nemo.frameweb.model.frameweb.ORMTemplate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createORMTemplateAdapter() {
		if (ormTemplateItemProvider == null) {
			ormTemplateItemProvider = new ORMTemplateItemProvider(this);
		}

		return ormTemplateItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (framewebProjectItemProvider != null)
			framewebProjectItemProvider.dispose();
		if (framewebModelItemProvider != null)
			framewebModelItemProvider.dispose();
		if (frameworkProfileItemProvider != null)
			frameworkProfileItemProvider.dispose();
		if (entityModelItemProvider != null)
			entityModelItemProvider.dispose();
		if (navigationModelItemProvider != null)
			navigationModelItemProvider.dispose();
		if (applicationModelItemProvider != null)
			applicationModelItemProvider.dispose();
		if (persistenceModelItemProvider != null)
			persistenceModelItemProvider.dispose();
		if (domainAssociationItemProvider != null)
			domainAssociationItemProvider.dispose();
		if (versionAttributeItemProvider != null)
			versionAttributeItemProvider.dispose();
		if (idAttributeItemProvider != null)
			idAttributeItemProvider.dispose();
		if (lobAttributeItemProvider != null)
			lobAttributeItemProvider.dispose();
		if (embeddedAttributeItemProvider != null)
			embeddedAttributeItemProvider.dispose();
		if (decimalAttributeItemProvider != null)
			decimalAttributeItemProvider.dispose();
		if (dateTimeAttributeItemProvider != null)
			dateTimeAttributeItemProvider.dispose();
		if (pageItemProvider != null)
			pageItemProvider.dispose();
		if (daoInterfaceItemProvider != null)
			daoInterfaceItemProvider.dispose();
		if (daoClassItemProvider != null)
			daoClassItemProvider.dispose();
		if (daoRealizationItemProvider != null)
			daoRealizationItemProvider.dispose();
		if (frontControllerClassItemProvider != null)
			frontControllerClassItemProvider.dispose();
		if (ioParameterItemProvider != null)
			ioParameterItemProvider.dispose();
		if (resultDependencyItemProvider != null)
			resultDependencyItemProvider.dispose();
		if (navigationAssociationItemProvider != null)
			navigationAssociationItemProvider.dispose();
		if (frontControllerMethodItemProvider != null)
			frontControllerMethodItemProvider.dispose();
		if (serviceClassItemProvider != null)
			serviceClassItemProvider.dispose();
		if (serviceInterfaceItemProvider != null)
			serviceInterfaceItemProvider.dispose();
		if (serviceGeneralizationItemProvider != null)
			serviceGeneralizationItemProvider.dispose();
		if (serviceControllerAssociationItemProvider != null)
			serviceControllerAssociationItemProvider.dispose();
		if (domainClassItemProvider != null)
			domainClassItemProvider.dispose();
		if (frontControllerDependencyItemProvider != null)
			frontControllerDependencyItemProvider.dispose();
		if (pageDependencyItemProvider != null)
			pageDependencyItemProvider.dispose();
		if (daoServiceAssociationItemProvider != null)
			daoServiceAssociationItemProvider.dispose();
		if (domainMethodItemProvider != null)
			domainMethodItemProvider.dispose();
		if (daoAttributeItemProvider != null)
			daoAttributeItemProvider.dispose();
		if (serviceMethodItemProvider != null)
			serviceMethodItemProvider.dispose();
		if (serviceAttributeItemProvider != null)
			serviceAttributeItemProvider.dispose();
		if (daoMethodItemProvider != null)
			daoMethodItemProvider.dispose();
		if (domainPackageItemProvider != null)
			domainPackageItemProvider.dispose();
		if (viewPackageItemProvider != null)
			viewPackageItemProvider.dispose();
		if (controllerPackageItemProvider != null)
			controllerPackageItemProvider.dispose();
		if (persistencePackageItemProvider != null)
			persistencePackageItemProvider.dispose();
		if (applicationPackageItemProvider != null)
			applicationPackageItemProvider.dispose();
		if (uiComponentItemProvider != null)
			uiComponentItemProvider.dispose();
		if (resultTypeItemProvider != null)
			resultTypeItemProvider.dispose();
		if (domainGeneralizationItemProvider != null)
			domainGeneralizationItemProvider.dispose();
		if (uiComponentFieldItemProvider != null)
			uiComponentFieldItemProvider.dispose();
		if (tagLibItemProvider != null)
			tagLibItemProvider.dispose();
		if (tagItemProvider != null)
			tagItemProvider.dispose();
		if (navigationCompositionPartItemProvider != null)
			navigationCompositionPartItemProvider.dispose();
		if (navigationCompositionWholeItemProvider != null)
			navigationCompositionWholeItemProvider.dispose();
		if (resultSetItemProvider != null)
			resultSetItemProvider.dispose();
		if (pageConstraintItemProvider != null)
			pageConstraintItemProvider.dispose();
		if (resultConstraintItemProvider != null)
			resultConstraintItemProvider.dispose();
		if (methodConstraintItemProvider != null)
			methodConstraintItemProvider.dispose();
		if (chainingConstraintItemProvider != null)
			chainingConstraintItemProvider.dispose();
		if (navigationGeneralizationItemProvider != null)
			navigationGeneralizationItemProvider.dispose();
		if (domainConstraintsItemProvider != null)
			domainConstraintsItemProvider.dispose();
		if (daoGeneralizationItemProvider != null)
			daoGeneralizationItemProvider.dispose();
		if (mappingLibItemProvider != null)
			mappingLibItemProvider.dispose();
		if (classMappingItemProvider != null)
			classMappingItemProvider.dispose();
		if (attributeMappingItemProvider != null)
			attributeMappingItemProvider.dispose();
		if (domainGeneralizationSetItemProvider != null)
			domainGeneralizationSetItemProvider.dispose();
		if (controllerItemProvider != null)
			controllerItemProvider.dispose();
		if (tagPropertyItemProvider != null)
			tagPropertyItemProvider.dispose();
		if (resultPropertyItemProvider != null)
			resultPropertyItemProvider.dispose();
		if (classMappingProperyItemProvider != null)
			classMappingProperyItemProvider.dispose();
		if (attributeMappingPropertyItemProvider != null)
			attributeMappingPropertyItemProvider.dispose();
		if (serviceRealizationItemProvider != null)
			serviceRealizationItemProvider.dispose();
		if (navigationGeneralizationSetItemProvider != null)
			navigationGeneralizationSetItemProvider.dispose();
		if (daoGeneralizationSetItemProvider != null)
			daoGeneralizationSetItemProvider.dispose();
		if (serviceGeneralizationSetItemProvider != null)
			serviceGeneralizationSetItemProvider.dispose();
		if (semanticPackageItemProvider != null)
			semanticPackageItemProvider.dispose();
		if (iriItemProvider != null)
			iriItemProvider.dispose();
		if (vocabularyModelItemProvider != null)
			vocabularyModelItemProvider.dispose();
		if (vocabularyItemProvider != null)
			vocabularyItemProvider.dispose();
		if (axiomItemProvider != null)
			axiomItemProvider.dispose();
		if (annotationItemProvider != null)
			annotationItemProvider.dispose();
		if (vocabularyConstraintsItemProvider != null)
			vocabularyConstraintsItemProvider.dispose();
		if (vocabularyAssociationItemProvider != null)
			vocabularyAssociationItemProvider.dispose();
		if (vocabularyPropertyItemProvider != null)
			vocabularyPropertyItemProvider.dispose();
		if (objectPropertyItemProvider != null)
			objectPropertyItemProvider.dispose();
		if (dataPropertyItemProvider != null)
			dataPropertyItemProvider.dispose();
		if (vocabularyDataTypeItemProvider != null)
			vocabularyDataTypeItemProvider.dispose();
		if (namedIndividualItemProvider != null)
			namedIndividualItemProvider.dispose();
		if (vocabularyClassItemProvider != null)
			vocabularyClassItemProvider.dispose();
		if (anonymousIndividualItemProvider != null)
			anonymousIndividualItemProvider.dispose();
		if (vocabularyLiteralItemProvider != null)
			vocabularyLiteralItemProvider.dispose();
		if (domainVocabularyAssociationItemProvider != null)
			domainVocabularyAssociationItemProvider.dispose();
		if (domainVocabularyPropertyItemProvider != null)
			domainVocabularyPropertyItemProvider.dispose();
		if (domainAttributeItemProvider != null)
			domainAttributeItemProvider.dispose();
		if (domainPropertyItemProvider != null)
			domainPropertyItemProvider.dispose();
		if (frontControllerTemplateItemProvider != null)
			frontControllerTemplateItemProvider.dispose();
		if (diTemplateItemProvider != null)
			diTemplateItemProvider.dispose();
		if (ormTemplateItemProvider != null)
			ormTemplateItemProvider.dispose();
	}

}
